version: 0.2
phases:
  install:
    commands:
      - echo install step...

  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region ap-northeast-1)
      - echo '-----------------------------------------------------------'
      - echo $ARUN
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t testecrtk .
      - docker tag testecrtk:latest 763614867397.dkr.ecr.ap-northeast-1.amazonaws.com/testecrtk:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 763614867397.dkr.ecr.ap-northeast-1.amazonaws.com/testecrtk:latest
      
