version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t awswitharun:latest .
      - docker tag awswitharun:latest 763614867397.dkr.ecr.ap-south-1.amazonaws.com/awswitharun:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 763614867397.dkr.ecr.ap-south-1.amazonaws.com/awswitharun:latest
      
